<?php
namespace App\Default\Entities;

use SPPMod\SPPEntity\SPPEntity;

/**
 * Class DummyEntity
 * Skeleton generated by SPP Entity Builder
 */
class DummyEntity extends \SPPMod\SPPEntity\SPPEntity
{
    // Custom domain logic here
}
