<?php
namespace App\Default\Entities;

use SPPMod\SPPEntity\SPPEntity;

/**
 * Class TestEditEntity
 * Skeleton generated by SPP Entity Builder
 */
class TestEditEntity extends \Base
{
    // Custom domain logic here
}
